name: Deploy
on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build Image
        run: |
          server_ver=$(npx -c 'echo "$npm_package_version"')
          cd jiber-server/examples/ha-kube-deployment
          docker build -t docker.io/jacobgrahn/jiber:$server_ver .

      - name: Push Image
        run: |
          server_ver=$(npx -c 'echo "$npm_package_version"')
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push docker.io/jacobgrahn/jiber:$server_ver

      - name: Deploy Demo Server
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 -d > ~/.kube/config
          server_ver=$(npx -c 'echo "$npm_package_version"')
          sed -i "s/jiber:latest/jiber:$server_ver/" jiber-server/examples/ha-kube-deployment/kube/jiber-deployment.yaml
          kubectl apply -f jiber-server/examples/ha-kube-deployment/kube
