name: Deploy
on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Push Demo Server
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: jacobgrahn/jiber
          tag: latest
          registry: docker.io
          dockerfile: jiber-server/examples/server/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
