name: Deploy
on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Run Tests
        run: ./install-and-test.sh

      - name: Publish to NPM
        run: |
          echo "${{ NPMRC }}" > ~/.npmrc
          cd jiber-client
          npm publish || echo 'publish failed'
          cd ../jiber-redis
          npm publish || echo 'publish failed'
          cd ../jiver-server
          npm publish || echo 'publish failed'

      - name: Build Image
        run: |
          cd jiber-server
          server_ver=$(npm run --silent version)
          cd examples/ha-kube-deployment
          docker build -t docker.io/jacobgrahn/jiber:$server_ver .

      - name: Push Image
        run: |
          cd jiber-server
          server_ver=$(npm run --silent version)
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push docker.io/jacobgrahn/jiber:$server_ver

      - name: Deploy Demo Server
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 -d > ~/.kube/config
          cd jiber-server
          server_ver=$(npm run --silent version)
          sed -i "s/jiber:latest/jiber:$server_ver/" examples/ha-kube-deployment/kube/jiber-deployment.yaml
          kubectl apply -f examples/ha-kube-deployment/kube
