name: Deploy
on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          cd jiber-server/examples/ha-kube-deployment
          docker build -t docker.io/jacobgrahn/jiber:latest .

      - name: Push Image
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push docker.io/jacobgrahn/jiber:latest
